# Generated by Django 2.2.9 on 2020-01-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_img_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img_profile',
        ),
    ]
