# Generated by Django 2.2.9 on 2020-01-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
    ]
